JavaCafe01/PdfViewer

- app/src/main/AndroidManifest.xml
Hi,
Thank you for this simple, lightweight PDF reader app!
Everything works for me except opening PDF files from other apps on my Android 7.1.1.
After digging a bit with Android Studio, I was able to resolve that by adding separate intent filters targeting the `application/pdf` MIME type, as suggested by [this answer](https://stackoverflow.com/a/5097734). Specifying both MIME and file extension in the same intent filter did not work for me, I think they have to be separate in order to target `.pdf` and `application/pdf` independently, otherwise both conditions would be required to match the file.
I think other users may benefit from this fix, so here is a pull request :wink:
Keep up the good work!
> Add application/pdf intent filters

- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
Sometimes I view very condensed PDFs, so I need to zoom further than only 3x. This pr increases the maximum zoom level to 5x, and accordingly increases by a little bit the mid zoom level (from the default 1.75x to 2x). This means that by double-tapping one time the zoom becomes 2x, with two double-taps it becomes 5x. So this pr also fixes #22 
I extracted some duplicate code spells into their own functions (see `setPdfViewConfiguration` and `setPageConfigurationAndLoad`).
I tested the app by opening PDFs multiple ways (i.e. sample file, downloaded file, view button on my Email client) and it always worked. Here is a test APK: [app-debug.zip](https://github.com/JavaCafe01/PdfViewer/files/4176962/app-debug.zip)
> Increase maximum zoom from 3x to 5x

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
On my device Pixel 3aXL running Android 10. The password EditText in the AlertDialog was not hiding the password as it was being typed.  I fixed this in commit 7fb2876.  The app would crash from a NullPointerException when one would try to open a PDF that was access from a web browser.  This is due to a changes in storage access rules on Android 10.  To overcome this issue I modified the manifest in commit c05aab7.
> Fixing Two Bugs

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gsnathan/pdfviewer/AboutActivity.java
- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/java/com/gsnathan/pdfviewer/Utils.java
- app/src/main/res/layout/activity_about.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/colors.xml
This PR fixes a couple of issues when using themes with a bright primary color, specifically:
- icons in the bottom bar remain white
- About activity title remains white
- bottom app bar has no elevation shadow (and therefore poor contrast with the content) 
It also improves colors of Changelog screen a little bit for increased readability:
> Fix some graphical issues with themes that have a light primary color

- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
I found myself trying to do that but it didn't work... so I made it work. :smiley: 
Also, since the user can now zoom out, I've changed the page fit policy so that the document is shown at full-width in landscape mode. This way, zoom level is consistent between vertical and landscape mode.
> Allow zooming out the document

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gsnathan/pdfviewer/SettingsActivity.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
This PR adds an option to prevent the app from being shown in launcher, for users (like me) that prefer getting rid of icons that aren't strictly necessary. The other ways to open the app (like selecting a file or a link to a PDF) are unaffected.
As you can see from the screenshot below, the option is set to show the app by default, so that a user must opt-in to hide the icon.
> Add option to show/hide app in launcher

- app/src/main/java/com/gsnathan/pdfviewer/MainIntroActivity.java
I've noticed that even though on Lollipop all storage permissions are automatically granted at install time (unlike Marshmallow and newer versions), the app intro still has the screen in which the user is asked to grant storage access.
This PR fixes this inconsistency by asking the user to grant storage access only on Marshmallow or higher.
> Don't show permission screen during intro on Lollipop devices

- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/res/layout/activity_main.xml
This PR greatly improves the logic for showing/hiding the bottom navigation bar for an overall better scrolling UX.
Before this PR, the bottom bar was hidden only when the user zoomed the document.
Now it behaves in the following way:
- the bottom bar gets hidden as soon as the user starts scrolling (which includes zooming)
- the user can show/hide the bottom bar with a single tap in any moment
- the bottom bar becomes visible again when the user scrolls at the top of the document (this doesn't work when the scroll handle is used to scroll to the top, I couldn't figure out why)
You can see the new behavior in the video here: https://streamable.com/1mqc23
While I was it, I couldn't refrain from doing some clean-ups to MainActivity in order to take advantage of newer Java features. 😅
I kept …
> Improve logic for showing/hiding the bottom bar

- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
This PR removes storage permission checks before opening the file picker, since SAF does not require any permission to access files.
Quoting [Android docs](https://developer.android.com/training/data-storage/shared/documents-files):
> Because the user is involved in selecting the files or directories that your app can access, **this mechanism doesn't require any system permissions**, and user control and privacy is enhanced.
> Do not ask for storage permission when opening file picker

- app/src/main/java/com/gsnathan/pdfviewer/DownloadPDFFile.java
- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/java/com/gsnathan/pdfviewer/Utils.java
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values/strings.xml
This PR fixes several issues I encountered while using the PDF download feature, namely:
- string resource ID is printed in the toast instead of actual error message in case of HTTP error response
- if storage access is not granted, the application crashes when opening a PDF link. I've fixed this in e1e99e2 by showing the temporary PDF file in the viewer instead of its copy in Download folder. This way, even if the user denies storage access, the app will continue to run as expected.
I've also added a toast that gets displayed after the user grants or denies write access (d8149e4) to help them understand why that permission was needed.
- if the same file gets redownloaded in temporary folder, overwrite the previous one instead of creating a copy with a different name (700d834). This is a …
> Miscellaneous fixes and minor improvements to PDF download feature

- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/res/xml/preferences.xml
In my experience using this app, anti-aliasing makes a big difference in rendering quality - especially with higher-resolution screens - so I find myself always enabling it.
I've made some tests on an old low-tier phone (a 2011 modded S3 Mini) and there is no noticeable performance impact caused by this setting.
I think it is safe to turn this option on for all new users, so that they can get the best possible quality without drawbacks by default.
> Turn on anti-aliasing by default

- app/src/main/java/com/gsnathan/pdfviewer/DownloadPDFFile.java
- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/java/com/gsnathan/pdfviewer/Utils.java
This PR changes download PDF feature so that the downloaded file is never written to cache folder, but is instead opened directly in-memory.
In this way, there will be no need to clear app cache anymore since nothing is ever written to it.
> Open downloaded file directly in-memory without saving it to cache folder

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/java/com/gsnathan/pdfviewer/SettingsActivity.java
With this PR, the app gains the ability to keep multiple PDFs open at the same time, leveraging [`documentLaunchMode` manifest activity attribute](https://developer.android.com/reference/android/R.attr#documentLaunchMode) added in Android Lollipop.
Now every document is opened in its own task (= Recents screen entry), whether it has been opened in-app or from an external app. Also, if the user opens a document that is already present in Recents screen, the corresponding activity gets brought to the foreground instead of launching a new instance of the app.
I had to make some changes to the way MainActivity is reopened when the user clicks on "Reload PDF" in settings. While I was at it, I've hidden the reload button if the user opens Settings while there is no opened document.
I've also …
> Multi-document support

- app/src/main/AndroidManifest.xml
While looking into the commit history, I've noticed that a very interesting comment in manifest file went lost at some point.
Since it answered a doubt I was having on the code, I re-added it. Maybe one day someone will find a better solution!
> Restore an useful comment in manifest

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gsnathan/pdfviewer/AboutActivity.java
- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/java/com/gsnathan/pdfviewer/SettingsActivity.java
- app/src/main/java/com/gsnathan/pdfviewer/Utils.java
In this PR I made some refactorings to leverage newer Android APIs and build features, namely:
- **view binding**: modern, safer and more performant replacement for `findViewById` (and `@ViewById` annotation). A nice extra benefit of this change is that MainActivity's onCreate() is no longer split between onCreate() and afterViews(), since we do the inflation manually.
- **`registerForActivityResult()` API** for requesting write permission, that we already use for opening file picker
I have also fixed two bugs:
- a **regression** introduced in multi-document PR (#88), that causes MainActivity to lose state on rotation when a file has been opened inside the app
- I have removed the option "Show app in launcher" on Android 10+ devices, since it does not work due to an Android change that we …
> Codebase modernization + critical bug fixes

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/password_dialog.xml
- app/src/main/res/menu/fab_menu.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values/strings.xml
This PR aims to make it clear to the user when opening the PDF fails due to an error or the document is protected by a password.
Currently, in both these scenarios the app shows only a blank screen without any indication.
With these changes, behavior changes as follows:
- if there is an error while opening the PDF, a toast with a generic error message is displayed
- if the PDF is protected, the user is asked to provide a password through the usual dialog (which has been revamped). If the entered password is wrong, a "Wrong password" toast is shown and the password prompt is displayed again
Since this last change makes the "Unlock PDF" button in the bottom bar useless, I removed it and made more difficult to accidentally dismiss the password request dialog.
Lastly, I've tweaked file …
> Improved handling of errors while opening a PDF

- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/java/com/gsnathan/pdfviewer/SettingsActivity.java
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru-rRU/strings.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
This PR removes the need for the "Reload document" button by automatically reloading the currently opened document when the user exits from the settings activity.
This automatic reload is better than the manual one for a couple of reasons:
- no extra activities are being opened (which would have been kept in Recents screen since multi-document implementation)
- the current position in the document (page number) doesn't get lost since the document is reloaded in the same activity
> Reload document automatically after closing settings

- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/res/layout/activity_main.xml
I've finally found a way to get the background color of the bottom bar working without breaking ripple.
It simply consists in setting the background color of the BottomNavigationView programmatically in onResume (so that it gets correctly updated when the user changes the theme).
Closes #101
> Fix bottom bar colors and ripple (this time for real)

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
This PR reworks the way MainActivity state is preserved to use `onSaveInstanceState` instead of AndroidAnnotations' `NonConfigurationInstance` annotation.
The main advantage of this old-school (but evergreen) method is that activity state is correctly preserved even after the app process gets terminated by the system (for example due to low memory constraints). Instead, `NonConfigurationInstance` uses `Activity.onRetainNonConfigurationInstance` under the hood, which works only with configuration changes.
With this change the app no longer needs to depend on AndroidAnnotations, so I removed the dependency altogether.
I've also used the aforementioned `onRetainNonConfigurationInstance` method to avoid re-downloading the entire PDF on screen rotation (and theme/settings update too) when the …
> Save activity state the Android way (and ditch AndroidAnnotations)

- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
This PR removes the content URI permission check that I added in 56c7304.
I originally added it to handle a rare crash that happens when the user re-opens the a PDF from Recents after a phone reboot. However, that check proved to be unreliable since it caused false negatives (see #107 and #98). To prevent the crash, we now catch exceptions that occur while retrieving the file name from a content provider.
I've taken this opportunity to simplify the logic for reading the incoming Intent URI and also fixed a small bug which caused the file picker to be re-opened every time the user rotated the screen when no document was opened.
Fixes #107 
Fixes #98
> Simplify logic for reading intent URI

- app/src/main/java/com/gsnathan/pdfviewer/AboutActivity.java
- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/java/com/gsnathan/pdfviewer/Utils.java
This PR makes some changes and fixes to sharing intents:
- fixes MIME type when sharing a PDF (it was incorrectly set to text/email before). One positive effect is that now Bluetooth sharing appears in the possible choices.
- adds ClipData to the sharing intent to fix #106
- works around sharing of downloaded PDFs by sharing only their URL. The proper way to share them (not just the URL) would be to store the file to cache folder and then use a FileProvider, but I hadn't time to implement it.
I've also noticed that the intent used to send an email to the developer was displaying the sharesheet instead of redirecting the user to the email app, so I fixed it.
**Bonus**: I've removed AndroidAnnotations from the list of used libraries. I should have done that in #105.
> Miscellaneous fixes to sharing intents

- app/src/main/java/com/gsnathan/pdfviewer/MainActivity.java
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
I've implemented a small quality-of-life change that I really felt the need for.
When the newly added "Keep the screen on" option is toggled, the screen will be kept on while the app is on screen.
Implementation detail: I set the KEEP_SCREEN_ON flag in `onResume` (instead of `onCreate`) so that the option takes effect as soon as the user exits from Settings, without the need to reopen the app.
> Add an option to keep the screen on while reading
